import { RepositoryReview } from './RepositoryReview';
import { useLocale } from './locale';
import type { LocalAnalysisResult } from '../../contracts/analysis';
import { DependencyGraph } from '../dependencies/DependencyGraph';
import { sourceHref, query, type LocalRepository } from './api';

export function LocalReport({ report, repo, view }: { report: LocalAnalysisResult; repo: LocalRepository; view: string }) {
  const { t } = useLocale();
  const href = (path: string, line: number) => sourceHref(repo.repository_id, repo.snapshot_id, path, line);
  const location = (item: {path: string; start_line: number}) => <a href={href(item.path, item.start_line)}>{item.path}:{item.start_line}</a>;
  if (view === 'Overview' && report.review) return <RepositoryReview report={report} repo={repo}/>;
  if (view === 'Dependencies') return report.dependencies ? <DependencyGraph graph={report.dependencies} localSource={href}/> : <p>{t('Dependency analysis is unavailable.')}</p>;
  if (view === 'Architecture') return <><p>{t('Assessment:')}<strong>{report.architecture?.primary ?? report.architecture?.summary ?? 'unavailable'}</strong></p>{report.architecture?.hypotheses.map(item => <article className="local-card" key={item.architecture}><h3>{item.architecture.replaceAll('_', ' ')}</h3><p>{t(item.assessment)} · {t(item.confidence)} confidence</p><ul>{item.reasons.map((reason, index) => <li key={index}>{reason.description} — {location(reason.location)}</li>)}</ul>{item.contradictions.map((reason, index) => <p key={index}>Contradiction: {reason.description} — {location(reason.location)}</p>)}{item.uncertainties.map(text => <p className="local-muted" key={text}>{text}</p>)}</article>)}</>;
  if (view === 'Testing') return <><p>{t('Coverage:')} {report.testing?.coverage ? `${report.testing.coverage.percent}% from supplied artifact` : t('No coverage artifact supplied. Tests were not executed.')}</p><h3>{t('Test files')}</h3>{report.testing?.test_files.length ? <ul>{report.testing.test_files.map(item => <li key={item.path}><a href={href(item.path, 1)}>{item.path}</a> · {item.framework ?? 'unknown framework'}</li>)}</ul> : <p>{t('No test files detected.')}</p>}<h3>{t('Service observations')}</h3>{report.testing?.services.map((item, i) => <article className="local-card" key={i}><h4>{item.name}</h4><p>{t(item.status)} — {location(item.location)}</p><p>{item.test_paths.join(', ') || t('No linked test files.')}</p></article>)}</>;
  if (view === 'Documentation') return report.documentation ? <><p className="local-muted">{t('Source-backed drafts. Review before using them as project documentation.')}</p><h3>{t('README draft')}</h3><pre className="local-pre">{report.documentation.readme}</pre><h3>{t('API draft')}</h3><pre className="local-pre">{report.documentation.api_markdown}</pre></> : <p>{t('Documentation analysis is unavailable.')}</p>;
  if (view === 'Refactoring') return report.refactoring?.recommendations.length ? <>{report.refactoring.recommendations.map((item, i) => <article className="local-card" key={i}><h3>{item.subject}</h3><p>{item.rationale}</p>{location(item.location)}<ul>{item.extractions.map((extraction, j) => <li key={j}>{extraction.responsibility}: {extraction.action}</li>)}</ul></article>)}</> : <p>{t('No supported refactoring candidates were found.')}</p>;
  if (view === 'Findings' || view === 'Security') {
    const security = new Set(report.items.filter(item => item.roles.includes('security') && item.finding).map(item => item.id));
    const findings = view === 'Security' ? report.findings.filter(item => security.has(item.id)) : report.findings;
    return findings.length ? <>{findings.map(item => <article className="local-card" key={item.id}><span className="local-badge">{t(item.severity)} · {t(item.source)}</span><h3>{item.issue_type.replaceAll('_', ' ')}</h3><p>{security.has(item.id) ? t('Potential security issue. Inspect the linked source; sensitive text is withheld from this summary.') : item.description}</p>{location(item.location)}{item.suggestion && !security.has(item.id) && <p>{item.suggestion}</p>}</article>)}</> : <p>{t('No findings were returned for this view. This does not establish that the code is free of defects.')}</p>;
  }
  return <><div className="local-metrics"><article><strong>{report.findings.length}</strong><span>{t('Findings')}</span></article><article><strong>{report.dependencies?.nodes.length ?? 0}</strong><span>{t('Source nodes')}</span></article><article><strong>{report.dependencies?.edges.length ?? 0}</strong><span>{t('Relationships')}</span></article></div><h3>{t('Analysis roles')}</h3><div className="local-role-grid">{report.roles.map(role => <article className="local-card" key={t(role.role)}><h4>{t(role.role)}</h4><span>{t(role.status)}</span>{role.error_code && <p>{role.error_code}</p>}</article>)}</div><p className="local-muted">{t('These are deterministic source analyses. AI explanations are not connected to this report.')}</p>{report.errors.map((error, index) => <p role="status" key={index}>{error.code}: {error.message}</p>)}<a className="local-download" download={`${repo.name}-analysis.json`} href={`/api/local/export?${query(repo)}`}>{t('Download full analysis')}</a></>;
}
